name: movie_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.9.1
  flutter_staggered_grid_view: ^0.3.3
  freezed_annotation: ^0.11.0+1
  flutter_bloc: ^6.0.1
  get_it: ^4.0.4
  injectable: ^1.0.4
  flushbar: ^1.10.4
  uuid: ^2.2.0
  auto_route: ^0.6.9
  meta: ^1.1.8
  kt_dart: ^0.8.0
  rxdart: ^0.24.1
  flutter_hooks: ^0.14.0
  styled_widget: ^0.1.1
  time: ^1.2.0
  transparent_image: ^0.1.0
  flutter_screenutil: ^4.0.2+2

  chopper: ^3.0.2
  connectivity: ^0.4.3+2
  json_annotation: ^3.0.1

  cupertino_icons: ^1.0.1

dev_dependencies:
  build_runner:
  freezed: ^0.11.5
  lint: ^1.2.0
  json_serializable: ^3.5.1
  injectable_generator: ^1.0.4
  auto_route_generator: ^0.6.9
  chopper_generator: ^3.0.4
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true